language: c
env:
  - ARCH=amd64
  - ARCH=i386
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - env: ARCH=i386
    - os: osx
install:
  - |
    export BRANCH=master
    if [ ! -x nim-$BRANCH/bin/nim ]; then
      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/nim nim-$BRANCH/
      cd nim-$BRANCH
      git clone --depth 1 git://github.com/nim-lang/csources csources/
      cd csources
      sh build.sh
      cd ..
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
    else
      cd nim-$BRANCH
      git fetch origin
      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
        bin/nim c koch
        ./koch boot -d:release
      fi
    fi
    cd ..
before_script:
    - export PATH="nim-$BRANCH/bin${PATH:+:$PATH}"
script:
    - nim c --cc:$CC --cpu:$ARCH --verbosity:0 -r coro.nim
cache:
  directories:
    - nim-master
    - nim-devel
notifications:
  email:
    on_success: never
    on_failure: never
